version: '3'

services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.2'
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yandex_db
    ports:
      - '5432:5432'
    depends_on: 
      - elasticsearch
  
  api:
    build: ./code/api
    command: sh -c "dockerize -wait http://elasticsearch:9200 && python3.8 src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  esdata1:
    driver: local
  postgres_data:
    driver: local