version: '3'

services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.2'
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    depends_on: 
      - elasticsearch
  
  api:
    build: ./code/api
    env_file:
      - docker.env
    command: >
      bash -c "sleep 10
      && python src/manage.py migrate
      && python src/manage.py makemigrations api
      && python src/manage.py migrate
      && python src/manage.py loaddata initial_data.json
      && python src/manage.py etl
      && python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on: 
      - db

volumes:
  esdata1:
    driver: local
  postgres_data:
    driver: local