# Generated by Django 3.1.5 on 2021-01-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('genre', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('imdb_rating', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'writers',
            },
        ),
        migrations.CreateModel(
            name='MovieWriters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.movies')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.writers')),
            ],
            options={
                'db_table': 'movie_writers',
            },
        ),
        migrations.CreateModel(
            name='MovieActors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.actors')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.movies')),
            ],
            options={
                'db_table': 'movie_actors',
            },
        ),
    ]
