# Generated by Django 3.1.5 on 2021-01-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'actors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieActors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_actors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('genre', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('plot', models.TextField(blank=True, null=True)),
                ('imdb_rating', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieWriters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_writers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'writers',
                'managed': False,
            },
        ),
    ]
